config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :newests

  resources :coins do
  	get :autocomplete_coin_full_name, :on => :collection
  end

  resources :categories

  post 'user_token' => 'user_token#create'
  get '/users/current-user', to: "current_user#show"
  get '/user_info', to: "users#show"
  put '/users', to: "users#update"
  resources :users
  resources :portfolios
  mount Knock::Engine => "/knock"


  resources :password_resets,     only: [:create, :update]

  get '/public_portfolio/:user_id/:portfolio_id', to: "users#public_portfolio"
  get '/sync', to: "users#data"
  post '/sync', to: "users#data_update"

end

app/models/newest.rb
class Newest < ApplicationRecord
	belongs_to :event

	mount_uploader :image, NewestImageUploader
end

app/controllers/newests_controller.rb
class NewestsController < ApplicationController
  before_action :set_newest, only: [:show, :edit, :update, :destroy]

  # GET /newests
  # GET /newests.json
  def index
    hash_params = params.fetch(:newests, {}).permit(:start_time, :end_time, category_ids: [], coin_ids: []).to_h

    @start_time = hash_params[:start_time]
    @end_time = hash_params[:end_time]
    @my_categories = hash_params[:category_ids]
    coin_ids = hash_params[:coin_ids].map(&:to_i).split(",") unless hash_params[:coin_ids].nil?
    @my_coins = Coin.where(id: coin_ids)

    @newests = Newest.joins(event: [:coin, :category])
                      .select('newests.id as id, newests.image as image, newests.created_at as created_at, newests.text as text, newests.link as link, events.start_time as start_time, events.end_time as end_time, categories.name as name, coins.id as coin_id, coins.logo as logo, coins.full_name as full_name')
                      .order('newests.created_at DESC')

    @newests = @newests.where("end_time >= ? OR (end_time IS NULL AND start_time >= ?)", @start_time, @start_time) unless @start_time.blank?
    @newests = @newests.where("start_time <= ?", @end_time) unless @end_time.blank?
    @newests = @newests.where(events: {category_id: @my_categories.map(&:to_i).split(",")}) unless @my_categories.nil?
    @newests = @newests.where(events: {coin_id: coin_ids}) unless coin_ids.nil?

  end

  # GET /newests/1
  # GET /newests/1.json
  def show
  end

  # GET /newests/new
  def new
    @newest = Newest.new
  end

  # GET /newests/1/edit
  def edit
  end

  # POST /newests
  # POST /newests.json
  def create

    @event = Event.new(event_params)

    if @event.save
      @newest = Newest.new(newest_params)
      @newest.event_id = @event.id
    else
      format.html { render :new }
      format.json { render json: @newest.errors, status: :unprocessable_entity }
      return
    end

    respond_to do |format|
      if @newest.save
        format.html { redirect_to @newest, notice: 'Newest was successfully created.' }
        format.json { render :show, status: :created, location: @newest }
      else
        format.html { render :new }
        format.json { render json: @newest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newests/1
  # PATCH/PUT /newests/1.json
  def update
    respond_to do |format|
      if @newest.update(newest_params)
        format.html { redirect_to @newest, notice: 'Newest was successfully updated.' }
        format.json { render :show, status: :ok, location: @newest }
      else
        format.html { render :edit }
        format.json { render json: @newest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newests/1
  # DELETE /newests/1.json
  def destroy
    @newest.destroy
    respond_to do |format|
      format.html { redirect_to newests_url, notice: 'Newest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newest
      @newest = Newest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newest_params
      params.fetch(:newest, {}).permit(:text, :link, :image)
    end

        # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.fetch(:event, {}).permit(:title, :describtion, :link, :start_time, :end_time, :coin_id, :category_id)
    end
end

app/helpers/newest_helper.rb
module NewestHelper
end

app/helpers/newests_helper.rb
module NewestsHelper
end

app/views/newests/_form.html.erb
<%= form_with(model: newest, local: true, :class => "form-horizontal") do |form| %>

  <% if newest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(newest.errors.count, "error") %> prohibited this newest from being saved:</h2>

      <ul>
      <% newest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= fields_for :event, @newest.event do |event_form| %>

  <div class="form-row">
    <div class="form-group col-sm-6">
      <div class='input-group date' id='datetimepicker_start'>
          <%= event_form.text_field :start_time, :class => "form-control", :placeholder => "Начало" %>
          <span class="input-group-addon">
              <i class="fa fa-calendar-o"></i>
          </span>
      </div>
    </div>
    <div class="form-group col-sm-6">
      <div class='input-group date' id='datetimepicker_end'>
          <%= event_form.text_field :end_time, :class => "form-control", :placeholder => "Завершение" %>
          <span class="input-group-addon">
              <i class="fa fa-calendar-o"></i>
          </span>
      </div>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col">
      <%= event_form.collection_select(:category_id, Category.order(name: :asc).all, :id, :name, {:prompt => "Категория"}, {:class=>'form-control', :id=>"categories"}) %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col">
      <%= event_form.collection_select(:coin_id, Coin.order(sort_order: :asc).all, :id, :full_name, {:prompt => "Монета"}, {:class=>'form-control', :id=>"coins"}) %>
    </div>
  </div>


  <div class="form-row">
    <div class="form-group col">
      <%= form.text_area :text, :class => "form-control", :placeholder => "Комментарий", :rows => "4" %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col">
      <%= form.text_field :link, :class => "form-control", :placeholder => "Ссылка на источник", :type => "url" %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col">
      <%= image_tag(@newest.image_url) if @newest.image? %>
      <%= form.file_field :image %>
      <%= form.hidden_field :image_cache %>
    </div>
  </div>

  <% end %>

  <div class="form-row">
    <div class="form-group col mb-0">
      <%= form.submit "Создать", :class => "btn btn-outline-primary float-right" %>
    </div>
  </div>

  <script type="text/javascript">
    $(function () {

      function formatCoin (coin) {
        if (!$(coin.element).data('coin-logo')) {
          return coin.text;
        }
        var $state = $(
          '<span><img src="' + $(coin.element).data('coin-logo') + '" class="img-flag" width=16 height = 16/> ' + coin.text + '</span>'
        );
        return $state;
      };

      $( "#categories, #coins" ).select2({
          theme: "bootstrap",
          language: "zh-TW"
      });

      // datetime picker
      $('#datetimepicker_start').datepicker({
        format: {
          toDisplay: function (date, format, language) {
              return moment(date).format("DD.MM.YYYY");
          },
          toValue: function (date, format, language) {
              return moment(date, "DD.MM.YYYY").format();
          }
        }
      });

      $('#datetimepicker_end').datepicker({
        format: {
          toDisplay: function (date, format, language) {
              return moment(date).format("DD.MM.YYYY");
          },
          toValue: function (date, format, language) {
              return moment(date, "DD.MM.YYYY").format();
          }
        }
      });

      $("#datetimepicker_start").on("changeDate", function (e) {
        $('#datetimepicker_end').datepicker('setStartDate', e.date);
      });

      $("#datetimepicker_end").on("changeDate", function (e) {
        $('#datetimepicker_start').datepicker('setEndDate', e.date);
      });

    });
  </script>

<% end %>

app/views/newests/_form_filters.html.erb
<%= form_tag('/newests', :method => "get", :html => {:class => "form-horizontal"}) do |form| %>
  <div class="card mb-3">
    <ul class="list-group list-group-flush">

      <li class="list-group-item">
        <h6 class="card-title">
          Период
        </h6>
        <div class="form-row">
          <div class="form-group col-sm-6">
            <div class='input-group date' id='datetimepicker_start'>
                <%= text_field_tag 'newests[start_time]', @start_time, :class => "form-control", :placeholder => "Начало" %>
                <span class="input-group-addon">
                    <i class="fa fa-calendar-o"></i>
                </span>
            </div>
          </div>
          <div class="form-group col-sm-6">
            <div class='input-group date' id='datetimepicker_end'>
                <%= text_field_tag 'newests[end_time]', @end_time, :class => "form-control", :placeholder => "Завершение" %>
                <span class="input-group-addon">
                    <i class="fa fa-calendar-o"></i>
                </span>
            </div>
          </div>
        </div>
      </li>

      <li class="list-group-item">
        <h6 class="card-title">
          Мои категории
        </h6>
        <div class="form-row">
          <div class="form-group col">
            <ul class="list-group categories_list">
              <% Category.order(name: :asc).all.each do |category| %>
                <li class="list-group-item list-group-item-action border-0">
                   <label class="form-check-label">
                      <%= check_box_tag "newests[category_ids][]", category.id, !@my_categories.nil? && @my_categories.include?(category.id.to_s), class: 'form-check-input' %>
                      <%= category.name %>
                   </label>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </li>

      <li class="list-group-item">
        <h6 class="card-title">
          Мои монеты
        </h6>
        <div class="form-row">
          <div class="form-group col">
            <%= text_field_tag 'js[coin_search]', nil, :class => "form-control", :id => "coin_search", :placeholder => "Начните вводить" %>
            <div id="coin_terms">
              
            </div>
          </div>
        </div>

        <div class="form-row coins_filter">
          <div class="form-group col">
            <ul id="coins_list" class="list-group list-group-flush">
              <% @my_coins.each do |coin| %>
                <li class="list-group-item border-0">
                  <img src ="<%= coin.logo_url %>" width=16 height=16 class='float_coin_logo'/>
                  <%= coin.full_name %>
                  <input type='hidden' name="newests[coin_ids][]" value="<%= coin.id %>">
                  <button type='button' class='close' aria-label='Close'>
                    <span aria-hidden='true'>&times;</span>
                  </button>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </li>
      <li class="list-group-item">
        <div class="form-row">
          <div class="form-group col mb-0">
            <%= submit_tag "Filter", :class => "btn btn-outline-primary float-right" %>
          </div>
        </div>
      </li>
    </ul>

  </div>

<% end %>




<script type="text/javascript">
  $(function () {

      $(".categories_list > .list-group-item-action").click(function(event) {
        $(event.target).find('.form-check-label').click();
      });

      $("ul").on('click', '.close', function(event) {
        $(event.target).closest('li').remove();
      });

      // coins autocompleter
      $( "#coin_search" ).autocomplete({
        minLength: 0,
        source: "<%= autocomplete_coin_full_name_coins_path %>",

        appendTo: "#coin_terms",

        focus: function( event, ui ) {
          $( "#coin_search" ).val( ui.item.label );
          return false;
        },
        select: function( event, ui ) {
          $("#coin_search").val("");
          $("#coins_list")
            .append($( "<li class='list-group-item border-0'></li>" )
              .append($("<img src =" + ui.item.logo.url + " width=16 height=16 class='float_coin_logo'/>"))
              .append(ui.item.value)
              .append($("<input type='hidden' name = 'newests[coin_ids][]' value='" + ui.item.id + "'>"))
              .append($("<button type='button' class='close' aria-label='Close'><span aria-hidden='true'>&times;</span></button>"))
            );

          return false;
        }
      }).data( "ui-autocomplete" )._renderItem = function( ul, item ) {
        return $( "<li class='list-group-item list-group-item-action'></li>" )
            .data( "ui-autocomplete-item", item )
            .append( "<img src =" + item.logo.url + " width=16 height=16 class='float_coin_logo'/><span>" + item.value + "</span>" )
            .appendTo( ul );
      };


      // datetime picker
      $('#datetimepicker_start').datepicker({
        format: {
          toDisplay: function (date, format, language) {
              return moment(date).format("DD.MM.YYYY");
          },
          toValue: function (date, format, language) {
              return moment(date, "DD.MM.YYYY").format();
          }
        }
      });

      $('#datetimepicker_end').datepicker({
        format: {
          toDisplay: function (date, format, language) {
              return moment(date).format("DD.MM.YYYY");
          },
          toValue: function (date, format, language) {
              return moment(date, "DD.MM.YYYY").format();
          }
        }
      });

      $("#datetimepicker_start").on("changeDate", function (e) {
        $('#datetimepicker_end').datepicker('setStartDate', e.date);
      });

      $("#datetimepicker_end").on("changeDate", function (e) {
        $('#datetimepicker_start').datepicker('setEndDate', e.date);
      });

  });
</script>

app/views/newests/_form_search.html.erb
<%= form_for("/newests", :method => "get", :html => {:class => "form-horizontal"}) do |form| %>

  <div class="form-row">
    <div class="form-group col mb-0">
      <div class='input-group'>
        <%= form.text_field :start_time, :class => "form-control", :placeholder => "Поиск" %>
        <span class="input-group-addon">
            <i class="fa fa-search"></i>
        </span>
      </div>
    </div>
  </div>

<% end %>

app/views/newests/edit.html.erb
<h1>Editing Newest</h1>

<%= render 'form', newest: @newest %>

<%= link_to 'Show', @newest %> |
<%= link_to 'Back', newests_path %>

app/views/newests/index.html.erb
    <div class="row">
      <div class="col-sm-10 main_header">
        <div class="main_header_center">
          <%= link_to 'ADD EVENT', new_newest_path, :class => "btn btn-outline-primary btn_add" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <p id="notice"><%= notice %></p>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-4 position-relative">
        <%= render 'form_filters' %>
      </div>

      <div class="col-sm-6">
        <div class="card">
          <div class="card-header">
            <%= render 'form_search' %>
          </div>

          <% if !@newests.blank? %>
            <ol class="newest_items list-group list-group-flush">
              <% @newests.each do |newest| %>
                <li class="newest_item list-group-item">
                  <div class="newest">
                    <div class="newest_item_header">

                      <a class="user_block" href="#">
                        <%= image_tag('ava_bis.jpg', :class => "avatar") %>
                        <span class="username">Otto Fon</span>
                      </a>

                      <div class="d-flex flex-row">

                          <div class="mr-auto">
                            <a class="coin_block" href="#">
                              <img class="logo_coin" src="<%= !newest.nil? ? "media/coin/logo/#{newest.coin_id}/#{newest.logo}" : '' %>" alt="">

                              <span class="coinname"><%= !newest.nil? ? newest.full_name : '' %></span>
                              <span class="newest_timestamp" title="5:40 PM - 8 Nov 2017">
                                <span class="_timestamp" data-time="1510141252"><%= time_ago_in_words(newest.created_at) %></span>
                              </span>
                            </a>
                          </div>
                          <div class="">
                            <span class="category_tag"><%= !newest.nil? ? "##{newest.name}" : '' %></span>
                          </div>
                          <div class="">
                            <span class="newest_butter_menu action_button">
                              <i class="fa fa-ellipsis-v"></i>
                            </span>
                          </div>

                      </div>
                    </div>
              

                    <p class="newest_text">
                      <span class="event_header"><%= !newest.nil? && !newest.start_time.nil? ? newest.start_time.strftime("%d %h %Y") : '' %></span> 
                      <span class="event_header"><%= !newest.nil? && !newest.end_time.nil? ? ' - '+ newest.end_time.strftime("%d %h %Y") : '' %></span> 
                      <%= newest.text %>
                      <br>
                      <a href="<%= newest.link %>" rel="nofollow" ><%= newest.link %></a>
                    </p>

                    <div class="feed_image">
                       <%= image_tag(newest.image_url, :class => "img-fluid") if !newest.image_url.nil? %>
                    </div>
                
                    <div>

                      <div class="newest_item_footer">
                        <button class="action_button">
                          <div class="icon_container" title="Date">
                            <span class="icon_date"></span>
                            <span class = "action_button_label">Date</span>
                          </div>
                        </button>

                        <div class="action_list">
                          <button class="text-danger action_button">
                            23 positive
                          </button>
                          <button class="text-success action_button">
                            2 negative
                          </button>
                        </div>

                        <button class="action_button">
                          <div class="icon_container" title="Share">
                            <span class="icon_share"></span>
                            <span class = "action_button_label">Share</span>
                          </div>
                        </button>
                      </div>
                    </div>
                  </div>
                </li>
              <% end %>
            </ol>
          <% else %>
            <p class="empty_case">Ничего не найдено</p>
          <% end %>
        </div>
      </div>

      <div class="col-sm-2">
        <div class="card mb-3">
          <div class="card-header">
            ...
          </div>
          <div class="card-body">
          </div>
        </div>
      </div>
    </div>

app/views/newests/new.html.erb
<div class="newest_form container">
	<div class="card">
		<div class="card-header">
			Сообщить о событии
		</div>
		<div class="card-body">
			<%= render 'form', newest: @newest %>
		</div>
	</div>
</div>

app/views/newests/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_newest_path(@newest) %> |
<%= link_to 'Back', newests_path %>