config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :newests

  resources :coins do
  	get :autocomplete_coin_full_name, :on => :collection
  end

  resources :categories

  post 'user_token' => 'user_token#create'
  get '/users/current-user', to: "current_user#show"
  get '/user_info', to: "users#show"
  put '/users', to: "users#update"
  resources :users
  resources :portfolios
  mount Knock::Engine => "/knock"


  resources :password_resets,     only: [:create, :update]

  get '/public_portfolio/:user_id/:portfolio_id', to: "users#public_portfolio"
  get '/sync', to: "users#data"
  post '/sync', to: "users#data_update"

end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	belongs_to :user
	has_many :portfolio_coin, dependent: :restrict_with_error
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user, only: [:index]
  skip_before_action :verify_authenticity_token, only: [:create, :update, :destroy]


  def index
    public_portfolios = Portfolio.joins(:user).where("users.activated", true).order("profit_24h DESC").all

    public_portfolios_array = []
    public_portfolios.each { |public_portfolio| 

      next if public_portfolio.price_original <= 0
      
      public_portfolio_element = {}

      public_portfolio_element["portfolio_id"]     = public_portfolio.portfolio_id
      public_portfolio_element["user_id"]          = public_portfolio.user.id
      public_portfolio_element["avatar"]           = public_portfolio.user.avatar.small.url
      public_portfolio_element["coins_count"]      = public_portfolio.coins_count
      public_portfolio_element["profit_24h"]       = public_portfolio.profit_24h
      public_portfolio_element["profit_7d"]        = public_portfolio.profit_7d

      if public_portfolio.user.first_name.to_s.empty? && public_portfolio.user.last_name.to_s.empty?
        public_portfolio_element["user_name"]      = "user#{public_portfolio.user.id}"
      else
        public_portfolio_element["user_name"]      = "#{public_portfolio.user.first_name} #{public_portfolio.user.last_name}"
      end

      public_portfolios_array << public_portfolio_element
    }
    render json: public_portfolios_array, status: 200
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
  end

  # GET /portfolios/new
  def new
    @portfolio = Portfolio.new
  end

  # GET /portfolios/1/edit
  def edit
  end

  # POST /portfolios
  # POST /portfolios.json
  def create

    current_portfolio = Portfolio.where(["user_id = ?", current_user.id]).first

    if(current_portfolio.nil?)
      @portfolio = Portfolio.new(portfolio_params)
      @portfolio.user_id = current_user.id
      respond_to do |format|
        if @portfolio.save
          format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
          format.json { render :show, status: :created, location: @portfolio }
        else
          format.html { render :new }
          format.json { render json: @portfolio.errors, status: :unprocessable_entity }
        end
      end
    else
      @portfolio = current_portfolio
      respond_to do |format|
        if @portfolio.update(portfolio_params)
          format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
          format.json { render :show, status: :ok, location: @portfolio }
        else
          format.html { render :edit }
          format.json { render json: @portfolio.errors, status: :unprocessable_entity }
        end
      end
    end


  end

  # PATCH/PUT /portfolios/1
  # PATCH/PUT /portfolios/1.json
  def update

    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_params
      params.fetch(:portfolio, {}).permit(:user_name, :coins_count, :profit_24h, :profit_7d)
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio, local: true) do |form| %>
  <% if portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% portfolio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Editing Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Show', @portfolio %> |
<%= link_to 'Back', portfolios_path %>

app/views/portfolios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Portfolios</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portfolios.each do |portfolio| %>
      <tr>
        <td><%= link_to 'Show', portfolio %></td>
        <td><%= link_to 'Edit', edit_portfolio_path(portfolio) %></td>
        <td><%= link_to 'Destroy', portfolio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Portfolio', new_portfolio_path %>

app/views/portfolios/new.html.erb
<h1>New Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Back', portfolios_path %>

app/views/portfolios/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_portfolio_path(@portfolio) %> |
<%= link_to 'Back', portfolios_path %>