config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :newests

  resources :coins do
  	get :autocomplete_coin_full_name, :on => :collection
  end

  resources :categories

  post 'user_token' => 'user_token#create'
  get '/users/current-user', to: "current_user#show"
  get '/user_info', to: "users#show"
  put '/users', to: "users#update"
  resources :users
  resources :portfolios
  mount Knock::Engine => "/knock"


  resources :password_resets,     only: [:create, :update]

  get '/public_portfolio/:user_id/:portfolio_id', to: "users#public_portfolio"
  get '/sync', to: "users#data"
  post '/sync', to: "users#data_update"

end

app/models/coin.rb
class Coin < ApplicationRecord
	has_many :event, dependent: :restrict_with_error

	mount_uploader :logo, CoinLogoUploader
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: [:show, :edit, :update, :destroy]

  autocomplete :coin, :full_name, :extra_data => [:logo]

  # GET /coins
  # GET /coins.json
  def index
    @coins = Coin.order(sort_order: :asc).all
  end

  # GET /coins/1
  # GET /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins
  # POST /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to @coin, notice: 'Coin was successfully created.' }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1
  # PATCH/PUT /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to @coin, notice: 'Coin was successfully updated.' }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1
  # DELETE /coins/1.json
  def destroy
    @coin.destroy
    respond_to do |format|
      format.html { redirect_to coins_url, notice: 'Coin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coin_params
      params.fetch(:coin, {}).permit(:name, :logo)
    end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/views/coins/_form.html.erb
<%= form_with(model: coin, local: true,  html: { multipart: true }) do |form| %>
  <% if coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
      <% coin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <p>
    <label>Logo</label>
    <%= image_tag(@coin.logo_url) if @coin.logo? %>
    <%= form.file_field :logo %>
    <%= form.hidden_field :logo_cache %>
  </p>

  <br>

  <%= form.text_field :symbol, :placeholder => "symbol" %>
  <%= form.text_field :coin_name, :placeholder => "coin_name" %>
  <br>
  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
  
<% end %>

app/views/coins/edit.html.erb
<h1>Editing Coin</h1>

<%= render 'form', coin: @coin %>

<%= link_to 'Show', @coin %> |
<%= link_to 'Back', coins_path %>

app/views/coins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coins</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= image_tag(coin.logo_url, size: "32x32") if !coin.logo_url.nil? %></td>
        <td><%= coin.full_name %></td>
        <td><%= link_to 'Show', coin %></td>
        <td><%= link_to 'Edit', edit_coin_path(coin) %></td>
        <td><%= link_to 'Destroy', coin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coin', new_coin_path %>

app/views/coins/new.html.erb
<h1>New Coin</h1>

<%= render 'form', coin: @coin %>
<br>
<%= link_to 'Back', coins_path %>

app/views/coins/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_coin_path(@coin) %> |
<%= link_to 'Back', coins_path %>